export const FS = {};

FS.systemId = "frontierscum-es";
FS.flagScope = FS.systemId;

FS.abilities = {
  grit: { label: "Aplomo" },
  slick: { label: "Brío" },
  wits: { label: "Seso" },
  luck: { label: "Suerte" },
};

FS.wantedStates = [
  { key: "deadOrAlive", label: "Vivo o Muerto" },
  { key: "dead", label: "Muerto" },
  { key: "alive", label: "Vivo" },
];

FS.miseryOptions = [
  { key: "", label: "Sin causa anotada" },
  { key: "hambre", label: "Hambre" },
  { key: "sed", label: "Sed" },
  { key: "frio", label: "Frío" },
  { key: "calor", label: "Calor" },
  { key: "desvelo", label: "Desvelo" },
  { key: "fiebre", label: "Fiebre" },
  { key: "veneno", label: "Veneno" },
  { key: "enfermedad", label: "Enfermedad" },
  { key: "mugre", label: "Mugre" },
  { key: "dolor", label: "Dolor" },
  { key: "borrachera", label: "Resaca o borrachera" },
];

FS.slotTypes = [
  { key: "head", label: "En la cabeza" },
  { key: "belt", label: "Al cinto" },
  { key: "back", label: "A la espalda" },
  { key: "pocket", label: "En los bolsillos" },
  { key: "horse", label: "En la montura" },
  { key: "condition", label: "Condiciones" },
];

FS.itemTypes = {
  gear: "gear",
  weapon: "weapon",
  protection: "protection",
  ammo: "ammo",
  medical: "medical",
  condition: "condition",
  item: "item",
};

FS.weaponClasses = [
  { key: "melee", label: "Melé" },
  { key: "ranged", label: "A distancia" },
  { key: "gun", label: "Arma de fuego" },
  { key: "thrown", label: "Arrojadiza" },
];

FS.protectionClasses = [
  { key: "hat", label: "Sombrero" },
  { key: "armor", label: "Armadura" },
  { key: "shield", label: "Escudo" },
];

FS.ammoClasses = [
  { key: "generic", label: "Genérica" },
  { key: "pistol", label: "Pistola" },
  { key: "rifle", label: "Rifle" },
  { key: "shotgun", label: "Escopeta" },
  { key: "arrow", label: "Flechas" },
];

FS.itemTypeLabels = {
  gear: "Equipo",
  weapon: "Arma",
  protection: "Protección",
  ammo: "Munición",
  medical: "Curación",
  condition: "Condición",
  item: "Objeto",
};

FS.skillSuggestions = [
  "Abrir cerraduras",
  "Acampar",
  "Apuestas",
  "Armas cortas",
  "Armas largas",
  "Armas negras",
  "Armas improvisadas",
  "Arquería",
  "Atar nudos",
  "Atletismo",
  "Azuzar animales",
  "Buscar rastros",
  "Cabalgar",
  "Carga y descarga",
  "Charlatanería",
  "Cazar",
  "Cocinar",
  "Conducir carretas",
  "Conducir diligencias",
  "Contar monedas",
  "Coser heridas",
  "Cuidar caballos",
  "Curar heridas",
  "Desenvainado rápido",
  "Disfrazarse",
  "Domar",
  "Emboscar",
  "Escalar",
  "Esconder alijos",
  "Esgrima",
  "Escuchar tras puertas",
  "Forzar cerraduras",
  "Forzar puertas",
  "Ganzúas",
  "Interrogar",
  "Intimidar",
  "Jugar cartas",
  "Jugar a los dados",
  "Leer personas",
  "Leer y escribir",
  "Lidiar con serpientes",
  "Medicina",
  "Mentirosos",
  "Montar guardia",
  "Nadar",
  "Navegar desiertos",
  "Negociar",
  "Ocultarse",
  "Orientación",
  "Pastorear",
  "Pelea de taberna",
  "Pelea sucia",
  "Persuadir",
  "Pistolas dobles",
  "Primeros auxilios",
  "Rastrear",
  "Reparar armas",
  "Rezar",
  "Robar bolsillos",
  "Sabotear",
  "Seguir pistas",
  "Sigilo",
  "Supervivencia",
  "Tácticas de banda",
  "Tasación",
  "Tirar cuchillos",
  "Tocar la armónica",
  "Trato con forajidos",
  "Trepar",
  "Trucos con cuchillos",
  "Vigilar",
  "Vivir del terreno",
  "Voluntad de hierro",
];

FS.tooltips = {
  name: "Nombre del personaje.",
  background: "Tu pinta, oficio o arquetipo principal.",
  wantedState: "Es el estado de la orden de busca. En el generador aleatorio sale de la tirada de la tabla y luego puedes cambiarlo a mano.",
  wantedCrime: "El delito o la razón por la que te buscan.",
  reward: "Recompensa en plata puesta sobre tu cabeza.",
  grit: "Aplomo: dolor, dureza, aguante y sangre fría.",
  slick: "Brío: rapidez, estilo, puntería y reflejos.",
  wits: "Seso: cabeza, intuición, saberes y calle.",
  luck: "Suerte: azar, destino y golpes improbables.",
  miserable: "Si estas Miserable no recuperas HP al descansar.",
  drunk: "Mientras estes borracho intercambias dos atributos.",
  hp: "Tus HP actuales.",
  maxHp: "Tu HP máximo.",
  aces: "Los Ases permiten repetir una tirada una vez.",
  silver: "La plata que llevas encima.",
  history: "Historia, trasfondo, relaciones y cicatrices.",
  skills: "Frontier Scum no trae una lista cerrada; aqui tienes sugerencias y puedes inventar las tuyas.",
  skillUse: "Las habilidades relevantes dan Ventaja a un chequeo de atributo si el DJ está de acuerdo.",
  head: "Hueco para sombrero u objetos en la cabeza.",
  belt: "Huecos rapidos al cinto.",
  back: "Huecos voluminosos a la espalda.",
  pocket: "Huecos pequeños de bolsillo.",
  horse: "Carga transportada por la montura.",
  condition: "Arrastra aquí estados, dolencias y condiciones activas del personaje.",
  restBrawl: "Recupera 1d4 HP mas 1 por cada fumar, beber o echar una siesta.",
  restFull: "Recupera 2 HP por cada necesidad cubierta; el confort dobla la curación.",
  dropCheck: "Chequeo al caer por debajo de 0 HP.",
  deathCheck: "Chequeo para ver si mueres o sobrevives por poco.",
  spendAce: "Gasta un As para repetir una tirada.",
  recoverAmmo: "Tras un tiroteo, chequea Suerte para recuperar una ranura de munición.",
  condition1: "Espacio para venenos, maldiciones, heridas raras o problemas activos.",
  condition2: "Espacio adicional para notas urgentes del personaje.",
  activeConditions: "Condiciones activas arrastradas a la ficha. Puedes abrirlas o borrarlas cuando cambien.",
  misery: "Selecciona la causa principal por la que estás Miserable.",
  drunkAbility1: "Primer atributo intercambiado por la borrachera.",
  drunkAbility2: "Segundo atributo intercambiado por la borrachera.",
  horseName: "Nombre de la montura.",
  horseLikes: "Lo que calma, alegra o motiva a la montura.",
  horseType: "Raza, aspecto o clase de montura.",
  horseVehicle: "Vehículo o uso especial, si aplica.",
  horseNotes: "Notas rápidas sobre carácter, cicatrices o rarezas.",
  horseStolen: "Marca si la montura es robada.",
  horseMorale: "Moral de la montura ante peligro o dolor.",
  npcMorale: "Moral del PNJ ante peligro, bajas o presión.",
  npcNotes: "Instinto, aspecto, relación, territorio o rumor clave.",
  npcAttack: "Ataque principal o modo de hacer daño.",
  npcProtection: "Blindaje, coberturas o reducción de daño.",
  npcSpecial: "Rarezas, trucos, emboscadas, venenos o reglas especiales.",
  itemName: "Nombre del objeto.",
  itemType: "Tipo de objeto dentro del sistema.",
  itemCost: "Coste en plata.",
  itemSlot: "Lugar donde suele llevarse encima.",
  itemSummary: "Resumen corto que aparecerá en tooltips y chat.",
  itemNotes: "Regla completa, detalle o texto de apoyo.",
  weaponClass: "Clase de arma.",
  weaponDamage: "Daño del arma. Puedes usar varios modos separados por '/'.",
  weaponRange: "Alcance narrativo del arma.",
  weaponHands: "Número de manos necesarias para usarla.",
  weaponAmmo: "Munición que consume o referencia de carga.",
  protectionClass: "Tipo de protección.",
  protectionReduction: "Cómo reduce o evita daño.",
  ammoClass: "Tipo de munición compatible.",
  ammoQuantity: "Cantidad abstracta que representa este objeto.",
  medicalHealing: "Efecto o curación que produce al usarse.",
  medicalUses: "Usos disponibles antes de agotarse.",
  useItem: "Usa el objeto y lanza su efecto al chat.",
  openItem: "Abre la ficha completa del objeto.",
  rollItem: "Lanza o usa este objeto.",
  consumeHat: "Usa el sombrero para ignorar por completo un golpe y perderlo.",
  useShield: "Aplica la reducción del escudo a este impacto.",
  applyDamage: "Aplica este daño al objetivo marcado, teniendo en cuenta su protección.",
};

FS.drOptions = [6, 8, 10, 12, 14, 16, 18];
FS.modifierOptions = [-4, -2, -1, 0, 1, 2, 4];
FS.negativeHpOptions = Array.from({ length: 13 }, (_, index) => index);
